// <auto-generated />
namespace SimpleInjector.CodeSamples
{
    using System;

    public sealed class ServiceProviderAdapter(Container container) : IServiceProvider
    {
        public object GetService(Type type) => container.TryGetInstance(type, out var instance) ? instance : null;
    }
}